services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: fastapi_api
    environment:
      SQL_SERVER:      "host.docker.internal"
      SQL_PORT:        "1433"
      SQL_DB:          "KursPython"
      SQL_USER:        "sa"
      SQL_PASS:        "TwojeAktualneHasloSa"          # ← ZMIEŃ NA PRAWDZIWE HASŁO
      REDIS_HOST:      "redis"
      REDIS_PORT:      "6379"
    ports:
      - "8000:8000"
    depends_on:
      - redis
